# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: bitnami/laravel

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
#      - image: circleci/mysql:5.7.22

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run: sudo dpkg --configure -a
      - run: sudo apt-get install -f
      - run: sudo apt-get clean && sudo apt-get update
      - run: sudo apt-get upgrade -y

      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs && node -v
      - run: sudo apt-get install -y npm

      - run: composer install -n --prefer-dist
      - run: npm install

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # Lint the code
      - run: composer run-script lint
      - run: composer run-script style

      - run: cd frontend
      - run: npm run lint

      # run tests!
      - run: vendor/bin/phpunit
